### ISSUE TITLE
Live feed

### ISSUE THREAD

**Issue by crazyslakr** [TedJuch/TedTournament#16]
Is the live feed for scores down, the San Diego St/Furman score didn't load up?

**Comment by crazyslakr** [comment]
Looks to be resolved, thanks!

**Comment by TedJuch** [comment]
I'm tracking some issues with my source but it should repair itself once the source issues are resolved.

**Comment by crazyslakr** [comment]
Think the feed went back down, all live source is missing from mastersheet
