### ISSUE TITLE
`startDate` column

### ISSUE THREAD

**Issue by heyltsjay** [TedJuch/TedTournament#3]
Hi! Thanks for this resource. It is driving my knockout bracket this year. In the future, it would be really nice to have a dedicated startDate column. Today I am doing a naïve string match based on the status `Mar 17 ~05:50 PM TV:TNT`

**Comment by TedJuch** [comment]
I've had this request before so let me see about splitting those apart into new attributes. So you're saying you'd like these as separate attributes:

Mar 17
~05:50 PM
TNT
